# Generated by Django 4.2.19 on 2025-02-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('condition', models.CharField(choices=[('NWT', 'New with Tags'), ('NWOT', 'New without Tags'), ('LN', 'Like New'), ('VGUC', 'Very Good'), ('GUC', 'Good'), ('DUC', 'Distressed')], max_length=4)),
                ('fit', models.CharField(choices=[('TF', 'Tight fit'), ('TTS', 'True to size'), ('RF', 'Relaxed fit')], max_length=3)),
                ('occasion', models.CharField(choices=[('CASUAL', 'Casual'), ('BUSINESS', 'Business'), ('FORMAL', 'Formal'), ('THEMED', 'Themed')], max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='closet.item')),
                ('size', models.CharField(choices=[('XXS', 'Double Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3)),
                ('clothing_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('SKIRT', 'Skirt'), ('DRESS', 'Dress'), ('JACKET', 'Jacket'), ('SWEATER', 'Sweater'), ('SHORTS', 'Shorts'), ('OTHER', 'Other')], max_length=10)),
            ],
            bases=('closet.item',),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='closet.item')),
                ('size', models.CharField(choices=[('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('12.5', '12.5'), ('13', '13')], max_length=4)),
            ],
            bases=('closet.item',),
        ),
    ]
