# Generated by Django 4.2.19 on 2025-03-17 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0003_remove_patron_patron_delete_librarian_delete_patron"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="closet_items/")),
                ("order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="closet.item",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
