# Generated by Django 4.2.19 on 2025-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0004_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.FileField(upload_to="closet_items/"),
        ),
    ]
