# Generated by Django 4.2.19 on 2025-03-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0005_alter_images_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="closet_items/"),
        ),
    ]
