# Generated by Django 4.2.19 on 2025-03-29 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet', '0007_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='access_list',
            field=models.ManyToManyField(blank=True, related_name='collections_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='privacy_setting',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='in_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='in_private_collection',
            field=models.BooleanField(default=False),
        ),
    ]
