# Generated by Django 4.2.19 on 2025-04-04 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet', '0008_collection_access_list_collection_privacy_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='access_list',
            field=models.ManyToManyField(blank=True, related_name='access_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
