# Generated by Django 4.2.19 on 2025-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0012_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('OUT', 'Checked Out'), ('IN', 'Checked In')], default='IN', max_length=10),
        ),
    ]
