# Generated by Django 4.2.19 on 2025-04-29 03:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0013_item_description_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 3, 50, 10, 514734, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='extended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='extension_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='extension_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
