# Generated by Django 4.2.19 on 2025-04-29 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0014_borrowrequest_end_date_borrowrequest_extended_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 6, 39, 43, 483601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='extension_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('RETURNED', 'Returned')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('RETURNED', 'Returned')], default='PENDING', max_length=10),
        ),
    ]
