# Generated by Django 4.2.19 on 2025-04-29 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0015_alter_borrowrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 13, 49, 38, 25578, tzinfo=datetime.timezone.utc)),
        ),
    ]
