# Generated by Django 4.2.19 on 2025-04-30 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0016_alter_borrowrequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_duration',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 0, 39, 45, 38968, tzinfo=datetime.timezone.utc)),
        ),
    ]
