# Generated by Django 4.2.19 on 2025-04-30 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0017_borrowrequest_borrow_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 0, 57, 29, 241894, tzinfo=datetime.timezone.utc)),
        ),
    ]
