# Generated by Django 4.2.19 on 2025-03-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarian",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="librarian_profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="patron",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="patron_profile_pictures/"
            ),
        ),
    ]
