# Generated by Django 4.2.19 on 2025-03-17 03:29

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default.jpg",
                upload_to=login.models.profile_picture_path,
            ),
        ),
    ]
