# Generated by Django 4.2.19 on 2025-03-17 03:51

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/hotel.jpg",
                upload_to=login.models.profile_picture_path,
            ),
        ),
    ]
