# Generated by Django 4.2.19 on 2025-03-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("patron", "Patron"), ("librarian", "Librarian")],
                default="patron",
                max_length=20,
            ),
        ),
    ]
