# Generated by Django 4.2.19 on 2025-03-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
